credentials:
  usernames:
    jsmith:
      name: John Smith
      password: $2a$12$6O0IQRdsdf7D3YS.4194zu3xsHMLIyrLTCq5lUqNXEDu.2TcH2qN6 # password
    rbriggs:
      email: rbriggs@abcdddd.com
      name: Rebecca Briggs
      password: $2a$12$6O0IQRdsdf7D3YS.4194zu3xsHMLIyrLTCq5lUqNXEDu.2TcH2qN6 # password
cookie:
  expiry_days: 30
  key: cfXedfsw123dvEd # Must be string
  name: chat_doc_v1_abe
preauthorized:
  emails:
  - melsby@abcdddd.com
event:
  location: vegas
redis:
  username: default
  password: default
  host: 127.0.0.1
  port: 6379
inference_server:
  url: llama-example-service.my.openshift.cluster.example.com